### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by BurntTayl** [mario-campos/xdccget#21]
ninja -C build
ninja: Entering directory `build'
[1/1] Linking target xdccget
FAILED: xdccget
cc  -o xdccget xdccget.p/xdccget.c.o xdccget.p/libircclient_src_libircclient.c.o -Wl,--as-needed -Wl,--no-undefined
ld.lld: error: undefined symbol: strtonum
>>> referenced by xdccget.c:283 (../xdccget.c:283)
>>>               xdccget.p/xdccget.c.o:(main)
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by mario-campos** [comment]
It looks like you're missing libbsd-dev.
